spring:
    application:
        name: url-shortener

    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/url_shortener_db

    jpa:
        hibernate:
            ddl-auto: validate

server:
    port: 8080

alias:
    size: 7
